server:
    port: ${port:8080}
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${mysql_password:12345678}
        url: jdbc:mysql://${mysql_url:localhost}:3306/todo
        username: ${mysql_user:root}
    jackson:
        time-zone: UTC
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
            javax:
                persistence:
                    validation:
                        mode: none
